### PR TITLE
Feature/password policy

### PR DESCRIPTION
**Pull request by awarrington0895**
Hey guys, please test this and approve/deny at your earliest convenience.  Thanks!

### CODE REVIEW

**Comment by awarrington0895** [comment]
[Check expiry information for accounts/passwords](https://trello.com/c/f3qZxuBa/35-check-expiry-information-for-accounts-passwords)

**Comment by brentl2008** [comment]
Looks good to me!

**Comment by brentl2008** [comment]
Whoops

**Review by brentl2008 — APPROVED** [review]
Nice documentation!

**Pull request merged**
